export const PERMISSIONS = {
    PATIENTS: {
        FINDALL: 'PATIENTS.FINDALL',
        FINDONE: 'PATIENTS.FINDONE',
        CREATE: 'PATIENTS.CREATE',
        UPDATE: 'PATIENTS.UPDATE',
        DELETE: 'PATIENTS.DELETE',
    },
    APPOINTMENTS: {
        FINDALL: 'APPOINTMENTS.FINDALL',
        FINDONE: 'APPOINTMENTS.FINDONE',
        CREATE: 'APPOINTMENTS.CREATE',
        UPDATE: 'APPOINTMENTS.UPDATE',
        UPDATESTATUS: 'APPOINTMENTS.UPDATESTATUS',
    },
    EXAMINATIONS: {
        FINDALL: 'EXAMINATIONS.FINDALL',
        FINDONE: 'EXAMINATIONS.FINDONE',
        CREATE: 'EXAMINATIONS.CREATE',
        UPDATE: 'EXAMINATIONS.UPDATE',
    },
};
